config/routes.rb
require 'sidekiq/web'
TvEpisodes::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :stations, only: [:index, :show] do
    get :download_list, on: :member, path: 'download_list/:authentication_token'
    resources :programs, only: [:new, :create, :destroy], controller: 'station/programs'
  end

  namespace :admin do
    root :to => 'pages#root'
    resources :users, :interactions, :episodes
    resources :genres, :networks, only: [:index, :show, :update, :delete]
    resources :programs do
      resources :images, :episodes, only: [:index]
    end
  end

  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    resources :programs, only: :index
  end

  # deprecated
  get "/user/:user_id/programs/t/:authentication_token" => 'user/programs#aired', :as => 'tokened_user_programs'
  get '/sitemap', :to => 'pages#sitemap', format: :xml

  resources :networks, only: [:index, :show]
  resources :programs, only: [:index, :show, :update] do
    get :guide, on: :collection
    get :download_list, on: :member, path: 'download_list/:authentication_token'

    resources :episodes, only: [:show, :update] do
      member do
        get :search
        get :download, path: 'download(/:authentication_token)'
      end
    end
  end


  # signup. account settings. Needs to be implemented simpler
  # resources :users, only: [:new, :create, :edit, :update], :module => 'user', :path => '/user'

  root :to => "pages#index"
end

app/models/program.rb
class Program < ActiveRecord::Base
  require 'open-uri'

  include Concerns::TVDB
  include Concerns::Sections
  include FriendlyId
  friendly_id :slug_candidates

  include PgSearch
  pg_search_scope :search,
    against: [
      [:name, 'A'],
      :overview, :network_name, :actors
    ]

  has_many :episodes, dependent: :destroy
  has_many :interactions, dependent: :nullify
  has_many :station_programs, dependent: :destroy
  has_many :images, dependent: :destroy

  has_many :stations, through: :station_programs
  has_and_belongs_to_many :genres

  belongs_to :network, counter_cache: true

  validates :tvdb_id, uniqueness: true
  validates :name, presence: true, if: :tvdb_updated?

  before_save :update_episodes_with_program_name

  scope :followed_by_any_user, -> { includes(:stations).where( 'stations.taggable_type'=> 'User') }
  scope :aired, -> { where.not(first_aired: nil) }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }

  def self.search_program query
    return all unless query.present?
    start_query, full_query = "%#{query}", "%#{query}%"
    where( %(programs.name ILIKE :query OR programs.search_name ILIKE :query OR overview ILIKE :full_query),
      { query: start_query, full_query: full_query }
    )
  end

  def airs_time
    read_attribute(:airs_time) || '9:00 PM'
  end

  def to_s
    name
  end

  def update_episodes_with_program_name
    return unless persisted?
    return unless name_changed?
    episodes.update_all(program_name: name)
  end

  def self.default_search_term_pattern
    "%{program_name} %{season_nr} %{filled_episode_nr}"
  end

  def followed_by_any_user?
    Program.followed_by_any_user.where(id: id).any?
  end

  def followed_by_user?(user)
    stations.user_stations.where('user_id = ?', user.id).any?
  end

  def banner
    images.with_fanart.sample
  end

  def series_banner
    images.with_image_type('series:graphical').all.sample
  end

  def slug_alternative_additions
    first_aired.try(:year) || tvdb_id
  end

  def slug_candidates
    [
      :name,
      [:name, :slug_alternative_additions]
    ]
  end

  def should_generate_new_friendly_id
    name_changed?
  end

  def new_serie?
    return false unless first_aired.present?
    first_aired.between?(2.months.ago, 2.months.from_now)
  end

  def tvdb_updated?
    last_checked_at.present?
  end
end

app/controllers/admin/programs_controller.rb
class Admin::ProgramsController < AdminAreaController
  before_filter :find_program, :except => [:index, :new, :create]

  # GET /admin_programs
  # GET /admin_programs.xml
  def index
    @programs = Program.order('active desc, status, name').page params[:page]
  end

  def show
    @last_episode           = @program.episodes.last_aired.first || @program.episodes.last
    @nav = program_nav_links
  end

  # GET /admin_programs/new
  # GET /admin_programs/new.xml
  def new
    @program = Program.new
  end

  # GET /admin_programs/1/edit
  def edit
  end

  # POST /admin_programs
  # POST /admin_programs.xml
  def create
    @program = Program.new program_params

    respond_to do |format|
      if @program.save
        format.html { redirect_to(@program, :notice => 'Program was successfully created.') }
        format.xml  { render :xml => @program, :status => :created, :location => @program }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @program.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin_programs/1
  # PUT /admin_programs/1.xml
  def update
    respond_to do |format|
      if @program.update_attributes program_params
        format.html { redirect_to([:admin, @program], :notice => 'Program was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @program.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_programs/1
  # DELETE /admin_programs/1.xml
  def destroy
    @program.destroy

    respond_to do |format|
      format.html { redirect_to(admin_programs_url) }
      format.xml  { head :ok }
    end
  end

  protected
  def find_program
    @program = Program.friendly.find(params[:id])
  end

  def program_params
    params.require(:program).permit!.tap do |params|
      params[:slug] = nil if params[:slug].blank?
    end
  end
end

app/controllers/api/programs_controller.rb
class Api::ProgramsController < Api::BaseController
  def index
    @programs = Program.order('status')
    @last_program = Program.order('updated_at').last

    if stale?(@last_program, public: true)
      render json: @programs.where('name IS NOT NULL').pluck(:name)
    end
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_filter :authenticate_user_from_token!, only: :download_list
  respond_to :html, :json, :js
  etag { current_user.try :id }

  def index
    @basic_program_scope = Program.active.includes(:network, :genres)

    if params[:q].present?
      @basic_program_scope = @basic_program_scope.order('status').search(params[:q])
    else
      @basic_program_scope = @basic_program_scope.order('status, programs.name')
    end

    @programs = @basic_program_scope.section(params[:page])

    if @program = exact_match_found?(params[:q])
      redirect_to @program
    else
      respond_with @programs
    end
  end

  def show
    @program = Program.friendly.find params[:id]

    if params[:q]
      @episodes = @program.episodes.includes(:downloads).order('season_nr desc, nr desc').search(params[:q])
    else
      if stale?(@program, public: true)
        @grouped_episodes = @program.episodes.includes(:downloads).order('season_nr desc, nr desc').group_by(&:season_nr)
        @personal_station = current_user.stations.personal.first if user_signed_in?
      end
    end
  end

  def update
    @program = find_program
    current_user.interactions.create({
      user: current_user,
      program: @program,
      interaction_type: "update program",
      format: params[:format] || 'html',
      end_point: url_for(@program),
      referer:          request.referer,
      user_agent:       request.user_agent
    })
    @program.delay.tvdb_full_update(true)
  end

  def download_list
    @program = find_program
    @episodes = @program.episodes.last_aired.downloaded
  end

  def guide
    @upcoming_episodes = Episode.active.next_airing_from(Date.today)
                          .includes(:program)
                          .limit(100)
    @past_episodes     = Episode.active.last_aired_from(Date.yesterday)
                          .section params[:page]
    @last_updated_episode = Episode.active.order(:updated_at).last
  end

  private
  def find_program
    Program.friendly.find(params[:id])
  end

  def exact_match_found?(query)
    return false if query.blank?
    Program.where('lower(name) = ?', query.downcase).first
  end

  def rounded_time
    Time.at(Time.now.to_i - (Time.now.to_i % 1.hour))
  end
end

app/controllers/station/programs_controller.rb
class Station::ProgramsController < Station::BaseController
  respond_to :html, :js

  def new
    @station = find_station
    @station_program = @station.station_programs.build
  end

  def create
    @program = find_program
    @station = find_station
    @station_program = @station.station_programs.create program: @program
    redirect_to :back
  end

  def destroy
    station = current_user.stations.friendly.find params[:station_id]
    program = Program.friendly.find params[:id]
    station.programs.delete program
    redirect_to :back
  end


  def find_program
    if params[:id]
      Program.friendly.find params[:id]
    else
      Program.find params[:station_program][:program_id]
    end
  end
end

app/helpers/admin/programs_helper.rb
module Admin::ProgramsHelper
end

app/helpers/program_helper.rb
module ProgramHelper
  def follow_program_button(personal_station, program)
    render 'programs/follow_button', personal_station: personal_station, program: program
  end

  def follow_link(personal_station, program)
    if program.followed_by_user? current_user
      link_to station_program_path(personal_station, program), method: :delete,
        class: 'btn btn-follow' do
          yield
        end
    else
      link_to station_programs_path(personal_station, id: program.id), method: :post,
        class: 'btn btn-follow' do
          yield
        end
    end
  end

  def follow_status_class(program)
    return '' unless user_signed_in?
    return 'following' if program.followed_by_user?(current_user)
    'not-following'
  end

  def active_season?(season, program, episode=nil)
    return season == episode.season_nr if episode
    program.current_season_nr == season
  end
end

app/views/programs/_follow_button.html.haml
= follow_link(personal_station, program) do
  %span.button-text.follow-text
    %i.icon-large.icon-eye-open
    Follow
  %span.button-text.following-text Following
  %span.button-text.unfollow-text &nbsp;Unfollow

app/views/programs/_program.html.haml
%tr[program]
  %td
    = link_to program.name, program
    - if program.status == 'Continuing'
      .label.label-success Running
  %td
    - if program.first_aired
      = l program.first_aired.to_date, format: :long
    - else
      \-
  %td
    - if next_episode = program.episodes.next_airing.first
      = pretty_date next_episode.airs_at
    - else
      \-
  %td= program.genres.map(&:name).uniq.to_sentence

app/views/programs/_program_details.html.haml
%ul.nav.nav-tabs#program-detail-tabs{data: {toggle: :tabs}}
  %li= link_to 'Banner', '#banner', 'data-toggle' => 'tab'
  %li= link_to 'More information', '#more-info', 'data-toggle' => 'tab'

.tab-content
  .tab-pane#banner
    .row-fluid
      .span8
        - if @program.series_banner
          %img{src: @program.series_banner.file.url, width: 700, height: 129}
        - else
          %img{src: 'http://placehold.it/700x129', width: 700, height: 129}
      .span4
        .panel
          %ul.unstyled
            %li== Last updated #{distance_of_time_in_words_to_now(@program.updated_at)} ago
            %li= link_to 'Imdb page', "http://www.imdb.com/title/#{@program.imdb_id}"
            - if current_user
              %li= link_to 'Request update', program_path(@program), id: :check_update, remote: true, method: :put, data: { disable_with: 'Requesting...' }

  .tab-pane#more-info
    %table.table
      %tr
        %th{width: 100} Runtime
        %td= pluralize( @program.runtime, 'minute')
        %th{width: 100} Genres
        %td= @program.genres.map(&:name).to_sentence
        - if @program.network
          %th{width: 100} Network
          %td{width: 150}= link_to @program.network.name, @program.network
      %tr
        %th Next episode
        %td
          - if episode = @program.episodes.next_airing.first
            = l episode.airs_at, format: :long
          - else
            \-
        %th Thetvdb rating
        %td= @program.tvdb_rating || 'Not available'
        %th Content rating
        %td= @program.contentrating || 'Not available'
      %tr
        %th.top Overview
        %td{colspan: 5}= @program.overview

app/views/programs/_season_tabs.html.haml
- selected_episode ||= nil
#season-tabs.tabbable.tabs-right{data: current_episode_data(selected_episode) }
  - cache [program, :season_tabs] do
    %ul.nav.nav-tabs#program-season-tabs
      - grouped_episodes.each do |season, episodes|
        %li{class: "s#{season}"}
          %a{href: "#s#{season}", 'data-toggle' => 'tab'}== Season #{season} (#{episodes.length})
    .tab-content
      - grouped_episodes.each do |season, episodes|
        - cache [:season, program, season] do
          .tab-pane{id: "s#{season}"}
            %table.table.table-bordered.table-striped
              %thead
                %th Title
                %th{width: 150} Airdate
              %tbody
                = render episodes, selected_episode: selected_episode, program: program

app/views/programs/banners.html.haml
%section#banners
  .page-header
    %h1
      = link_to @program.name, @program
      %small banners

  %ul.nav.nav-tabs
    - @image_types.each do |image_type|
      %li{:class => (:active if image_type == @image_type)}
        = link_to image_type, url_for(params.merge(:image_type => image_type))

  .page-header
    %h3
      Banners
      - unless @program.series_image.present?
        %small
          %span.label.warning#placeholder No placeholder selected

  = form_for @program, :remote => true, :class => 'form-stacked' do |f|
    - if @images.any?
      %fieldset
        = render :partial => 'images/image', :collection => @images, :locals => {:f => f}

app/views/programs/guide.html.haml
- page_title "Episode guide"
%h3 Full guide
%section
  .row
    .span3
      .page-header
        %h4 Stations
      = render 'application/station_list'
    .span6
      .page-header
        %h4 Recently aired
        %dl#past-episodes
          = render 'episodes/past_episodes', |
            past_episodes: @past_episodes, last_updated_episode: @last_updated_episode

    .span3
      .page-header
        %h4 Next airing
      .well
        - cache [:guide, @last_updated_episode] do
          = render 'episodes/next_airing', next_episodes: @upcoming_episodes

app/views/programs/guide.js.erb
<% content = render "episodes/past_episodes",
  past_episodes: @past_episodes, last_updated_episode: @last_updated_episode %>
$('.pagination').remove();
$('#past-episodes').append('<%= j content %>');

app/views/programs/index.html.haml
%section
  .page-header
    %h1
      - if params[:search]
        == Results for #{params[:search]}
      - else
        List all programs
  .panel
    = form_tag programs_path, method: :get, class: 'form-search' do
      %label{for: :q} Search
      = text_field_tag :q, params[:q], class: 'search-query"'
      = submit_tag 'Go', class: 'btn'
  - if @programs.any?
    %table.table.table-striped#programs
      %thead
        %tr
          %th Program name
          %th First aired
          %th Next episode
          %th Genres
      %tbody
        = render @programs
    .pagination
      = link_to '>', url_for(params.merge(page: (params[:page] || 1).succ)), class: 'next_page'
  - else
    %p.nothing
      No programs found!

app/views/programs/index.js.erb
$('#programs tbody').append('<%= j render(@programs) %>');
<% if @basic_program_scope.section(params[:page].to_i.succ).any? %>
  content = '<%= j link_to ">", url_for(params.merge(page: (params[:page] || 1).succ)), class: :next_page %>';
  $('.pagination').html(content);
<% else %>
  $('.pagination').remove();
<% end %>

app/views/programs/show.html.haml
- page_title @program.name
- meta_description @program.overview

%section.program{ class: follow_status_class(@program) }
  .page-header
    .row
      .span10
        %h1
          = @program.name
          %small
            = @program.status
            - if current_user.try(:trusted?)
              = link_to download_list_program_path @program, authentication_token: current_user.authentication_token, format: :rss do
                %i.icon-rss
      .span2
        - if user_signed_in?
          .pull-right= follow_program_button(@personal_station, @program)
  = render 'program_details'

  %section.episodes
    .page-header
      %h3
        Episodes
        = form_tag program_path(@program), method: :get, class: 'form-search' do
          %label{for: :q} Search
          = text_field_tag :q, params[:q], class: 'search-query"'
          = submit_tag 'Go', class: 'btn'

    - if params[:q]
      %table.table.table-bordered.table-striped
        %thead
          %th Title
          %th{:width => 150} Airdate
        %tbody
          = render @episodes
    - else
      = render 'season_tabs', program: @program, grouped_episodes: @grouped_episodes

app/views/programs/update.js.haml
- if @image_id
  :plain
    $('html, body').animate({
        scrollTop: $('#image_#{@image_id}').offset().top
    }, 1000);
    $('#placeholder').hide('500');