config/routes.rb
require 'sidekiq/web'
TvEpisodes::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :stations, only: [:index, :show] do
    get :download_list, on: :member, path: 'download_list/:authentication_token'
    resources :programs, only: [:new, :create, :destroy], controller: 'station/programs'
  end

  namespace :admin do
    root :to => 'pages#root'
    resources :users, :interactions, :episodes
    resources :genres, :networks, only: [:index, :show, :update, :delete]
    resources :programs do
      resources :images, :episodes, only: [:index]
    end
  end

  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    resources :programs, only: :index
  end

  # deprecated
  get "/user/:user_id/programs/t/:authentication_token" => 'user/programs#aired', :as => 'tokened_user_programs'
  get '/sitemap', :to => 'pages#sitemap', format: :xml

  resources :networks, only: [:index, :show]
  resources :programs, only: [:index, :show, :update] do
    get :guide, on: :collection
    get :download_list, on: :member, path: 'download_list/:authentication_token'

    resources :episodes, only: [:show, :update] do
      member do
        get :search
        get :download, path: 'download(/:authentication_token)'
      end
    end
  end


  # signup. account settings. Needs to be implemented simpler
  # resources :users, only: [:new, :create, :edit, :update], :module => 'user', :path => '/user'

  root :to => "pages#index"
end

app/models/network.rb
class Network < ActiveRecord::Base
  include FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  has_many :programs

  scope :active, -> { where active: true }
  scope :inactive, -> { where active: false }

  validates :name, presence: true

  after_save { Network.delay.update_program_state(self.id) }

  def update_program_state
    if active
      programs.map(&:update_active_state!)
    else
      programs.update_all(active: false)
    end
  end

  def self.update_program_state(id)
    genre = Network.find(id)
    genre.update_program_state
  end
end

app/controllers/admin/networks_controller.rb
class Admin::NetworksController < AdminAreaController
  def index
    @networks = Network.order('programs_count desc, name')
  end

  def show
    @network = Network.find(params[:id])
    program_scope = @network.programs.order('active desc, status, first_aired desc')
    @programs = program_scope.section params[:page]
    @next_programs = program_scope.section params[:page].to_i.succ
  end

  def update
    @network = Network.find(params[:id])
    @network.update_attribute :active, params[:active]
  end

  def destroy
    @network = Network.find(params[:id])
    @network.destroy

    redirect_to admin_networks_path
  end
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
  def index
    @networks = Network.order('name')
  end

  def show
    @network = Network.find params[:id]
    @programs = @network.programs.aired.where(status: 'Continuing').order('first_aired desc')
  end
end

app/views/admin/networks/_network.html.haml
%tr[network]{ class: ('success' if network.active) }
  %td= link_to network.name, [:admin, network]
  %td= pluralize network.programs_count, 'program'
  %td
    = link_to admin_network_path(network, active: !network.active), method: :patch, data: { remote: true, 'disable-with' => '...' } do
      - if network.active
        %i.icon-ok.text-success
      - else
        %i.icon-remove.text-danger

app/views/admin/networks/index.html.haml
%h1 Network listing

%table.table.table-striped.table-hover.table-bordered
  %thead
    %th Name
    %th Nr of programs
    %th Active
  %tbody
    = render @networks

app/views/admin/networks/show.html.haml
%section
  .page-header
    %h1== #{@network.name}'s programs

  %table.table.table-hover
    %thead
      %tr
        %th Name
        %th Next episode
        %th Status
        %th Last update
        %th Last checked
        %th Controls

    %tbody
      = render @programs

  .pagination
    = link_to '>', url_for(params.merge(page: (params[:page] || 1).succ)), class: 'next_page'

app/views/admin/networks/show.js.erb
$('tbody').append('<%= j render(@programs) %>');
<% if @next_programs.any? %>
  content = '<%= j link_to ">", url_for(params.merge(page: (params[:page] || 1).succ)), class: :next_page %>';
  $('.pagination').html(content);
<% else %>
  $('.pagination').remove();
<% end %>

app/views/admin/networks/update.js.erb
content = $('<%= j render @network %>');
$('#<%= dom_id(@network)%>').replaceWith(content);