config/routes.rb
require 'sidekiq/web'
TvEpisodes::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :stations, only: [:index, :show] do
    get :download_list, on: :member, path: 'download_list/:authentication_token'
    resources :programs, only: [:new, :create, :destroy], controller: 'station/programs'
  end

  namespace :admin do
    root :to => 'pages#root'
    resources :users, :interactions, :episodes
    resources :genres, :networks, only: [:index, :show, :update, :delete]
    resources :programs do
      resources :images, :episodes, only: [:index]
    end
  end

  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    resources :programs, only: :index
  end

  # deprecated
  get "/user/:user_id/programs/t/:authentication_token" => 'user/programs#aired', :as => 'tokened_user_programs'
  get '/sitemap', :to => 'pages#sitemap', format: :xml

  resources :networks, only: [:index, :show]
  resources :programs, only: [:index, :show, :update] do
    get :guide, on: :collection
    get :download_list, on: :member, path: 'download_list/:authentication_token'

    resources :episodes, only: [:show, :update] do
      member do
        get :search
        get :download, path: 'download(/:authentication_token)'
      end
    end
  end


  # signup. account settings. Needs to be implemented simpler
  # resources :users, only: [:new, :create, :edit, :update], :module => 'user', :path => '/user'

  root :to => "pages#index"
end

app/views/layouts/admin/application.html.haml
!!! 5
%html{html_attrs('en')}
  %head
    %meta{'http-equiv' => 'Content-Type', :content => 'text/html; charset=utf-8'}
    %meta{name: :viewport, content: 'width=device-width, initial-scale=1.0'}
    = stylesheet_link_tag :admin
    %meta{:name=>"robots",        :content=>"index, follow"}
    %meta{:name=>"revisit-after", :content=>"1 days"}
    %meta{:name=>"author",        :content=>"me"}
    %meta{:name =>'csrf-token',    :content => form_authenticity_token}
    %meta{:name =>'csrf-param',    :content => 'authenticity_token'}

    %title TV guide Admin
    = yield :head
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          -# responsive menu for small displays
          %a.btn.btn-navbar{'data-toggle' => 'collapse', 'data-target' => '.nav-collapse'}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar

          = link_to 'Admin', admin_root_path, class: :brand

          -# everything inside this div is hidden for small displays
          .nav-collapse.collapse
            = render 'application/admin/navigation'
            %ul.nav.pull-right
              %li= link_to "welcome #{current_user.login.humanize}", edit_admin_user_path(current_user)
              %li= link_to 'Back to the website', root_path

    - if content_for?(:hero_unit)
      = yield(:hero_unit)
    #main.container-fluid
      = render 'notifications_and_errors'
      = yield
    %footer
    = yield :bottom
    = render 'bottom_js', locals: { admin: true }