config/routes.rb
require 'sidekiq/web'
TvEpisodes::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :stations, only: [:index, :show] do
    get :download_list, on: :member, path: 'download_list/:authentication_token'
    resources :programs, only: [:new, :create, :destroy], controller: 'station/programs'
  end

  namespace :admin do
    root :to => 'pages#root'
    resources :users, :interactions, :episodes
    resources :genres, :networks, only: [:index, :show, :update, :delete]
    resources :programs do
      resources :images, :episodes, only: [:index]
    end
  end

  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    resources :programs, only: :index
  end

  # deprecated
  get "/user/:user_id/programs/t/:authentication_token" => 'user/programs#aired', :as => 'tokened_user_programs'
  get '/sitemap', :to => 'pages#sitemap', format: :xml

  resources :networks, only: [:index, :show]
  resources :programs, only: [:index, :show, :update] do
    get :guide, on: :collection
    get :download_list, on: :member, path: 'download_list/:authentication_token'

    resources :episodes, only: [:show, :update] do
      member do
        get :search
        get :download, path: 'download(/:authentication_token)'
      end
    end
  end


  # signup. account settings. Needs to be implemented simpler
  # resources :users, only: [:new, :create, :edit, :update], :module => 'user', :path => '/user'

  root :to => "pages#index"
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  include ActionView::Helpers::SanitizeHelper
  include Concerns::Sections

  mount_uploader :thumb, ::ImageUploader

  include PgSearch
  multisearchable against: [:title, :description],
    using: {
      tsearch: {dictionary: "english"}
    }
  pg_search_scope :search,
    against: [
      [:title, 'A'],
      :description
    ]

  belongs_to :program, touch: true
  has_many :interactions, dependent: :nullify
  has_many :downloads, dependent: :destroy
  has_many :stations, through: :program

  validates :title, :season_nr, :program_id, :program_name, presence: true

  # used for guide view
  scope :next_airing_order,       ->{ order('airs_at asc').includes(:program) }
  scope :next_airing,             ->{ airs_at_in_future.next_airing_order }
  scope :next_airing_at,          ->(time){ where('airdate < ?', time.to_date).order('airs_at desc').where.not(airs_at: nil) }
  scope :next_airing_from,        ->(date){ where('airdate > ?', date).order('airdate asc').where.not(airdate: nil) }
  scope :last_aired,              ->{ airs_at_in_past.order('airs_at desc').includes(:program, :downloads) }
  scope :last_aired_at,           ->(time){ last_aired.where('date(episodes.airs_at) < ?', time.to_date) }
  scope :last_aired_from,         ->(date){ where('episodes.airdate <= ?', date).order('airdate desc').where.not(airdate: nil) }
  scope :downloaded,              ->{ includes(:downloads).where.not(downloads: { id: nil } ).references(:downloads) }
  scope :without_download,        ->{ includes(:downloads).where(downloads: { id: nil } ).references(:downloads) }
  scope :watched_by_a_user,       ->{ includes(:stations).where(stations: {taggable_type: 'User'}) }
  scope :downloadable,            ->{ without_download.watched_by_a_user }
  scope :airs_at_in_future,       ->{ where('airs_at > ?', Time.zone.now) }
  scope :airs_at_in_past,         ->{ where('airs_at < ?', Time.zone.now) }
  scope :airs_at_inside,          ->(first_date, last_date) { where('airs_at > :first_date AND airs_at < :last_date', \
                                      {first_date: first_date, last_date: last_date}) }
  scope :with_same_program,       ->(episode) { where('episodes.program_id = ?', episode.program_id) }
  scope :active,                  ->{ includes(:program).where('programs.active = ?', true).references(:program) }

  before_validation :update_program_name
  before_validation :update_sort_order

  delegate :new_serie?, to: :program

  # attribute overwrites
  def airdate=(date)
    super(date)
    set_airs_at_from_airdate date
  end

  def set_airs_at_from_airdate(date)
    return unless date.present?
    return unless program.try(:airs_time)
    Time.zone = self.program.time_zone_offset
    self.airs_at = Time.zone.parse( %(#{date} #{self.program.airs_time}) )
  rescue ArgumentError #invalid date
    date
  end

  def episode
    "%02d" % nr.to_i
  end

  def age
    return -1 unless airdate
    (Date.today - airdate).to_i
  end

  def aired?
    age >= 0
  end

  def search_query(extra_terms)
    ([] << interpolated_search_term << extra_terms) * ' '
  end

  def program_name
    read_attribute(:program_name) || program.try(:name)
  end

  def season_and_episode
    "S#{"%02d" % season_nr}E#{episode}"
  end

  def full_episode_title
    "#{season_and_episode} - #{title}"
  end

  def full_title
    "#{program_name} - #{full_episode_title}"
  end

  def filename
    "#{program_name}_#{season_and_episode}_-_#{title}".parameterize
  end

  def to_s
    filename
  end

  def to_i
    nr.to_i
  end

  def to_param
    "#{id}-#{title.parameterize}"
  end

  def qualities
    ['hd']
  end

  def download(quality='hd')
    logger.info "="*30
    logger.info "Getting #{quality} from #{search_url}"
    logger.info "="*30

    next_page   = Browser.agent.get( search_url ).forms.last.submit
    if (download_links = next_page.links_with(text: 'Download')).any?
      self.downloads.first_or_initialize( download_type: quality ).tap do |download|
        download.origin = strip_tags(Nokogiri::HTML(next_page.body).css('td label').last.to_s)
        download.file   = download_links.last.click
        download.save
      end
    else
      logger.info "No downloads found at #{search_url}"
      false
    end
  rescue Mechanize::ResponseCodeError => e
    logger.debug "Could not download episode: #{e.message}"
    false
  end

  def download_with_reschedule
    return if self.download('hd')

    # reschedule if 'fresh'
    downloadable? && self.delay_for(1.hour).download_with_reschedule
  end

  def max_download_time
    airdate + 7.days
  end

  # < means before max_download_time
  def downloadable?
    Date.today < max_download_time
  end

  def searcher
    @searcher ||= ::NzbSearch.new.tap do |searcher|
      searcher.search_terms = "#{self.interpolated_search_term} #{searcher.default_terms}"
      searcher.age = self.age
    end
  end

  def search_url
    searcher.link
  end

  # api methods
  def self.tvdb_client
    TvdbParty::Search.new(TVDB_API)
  end

  def tvdb_client
    self.class.tvdb_client
  end

  def apply_tvdb_attributes tvdb_result
    self.program_name = program.name if program
    self.tvdb_id      = tvdb_result.id
    self.nr           = tvdb_result.number
    self.season_nr    = tvdb_result.season_number
    self.title        = tvdb_result.name || 'TBA'
    self.description  = tvdb_result.overview
    self.airdate      = tvdb_result.air_date
    self.remote_thumb_url = tvdb_result.thumb if program.try(:active?)
    self
  end

  def self.from_tvdb tvdb_result, program=nil
    if program
      _new = self.new( program_id: program.id )
    else
      _new = self.new
    end
    _new.apply_tvdb_attributes tvdb_result
  end

  def self.tvdb_ids
    @tvdb_ids ||= tvdb_id.all
  end

  def self.updates timestamp=Time.now, only_existing = true
    updates = tvdb_client.get_episodes_updates( timestamp.to_i )['Episode']
    only_existing ? updates.reject{|tvdb_id| !tvdb_ids.include?(tvdb_id.to_s) } : updates
  end

  def tvdb_episode
    tvdb_client.get_episode_by_id self.tvdb_id
  end

  def tvdb_update_hash
    tvdb_client.get_episode_by_id self.tvdb_id
  end

  def tvdb_update
    self.apply_tvdb_attributes tvdb_episode
    save!
  end

  def self.get_episodes_by_tvdb_id tvdb_id
    tvdb_client.get_all_episodes_by_id( tvdb_id ).reject{|e| e.season_number.to_i == 0}
  end

  def update_program_name
    program_name = program.name if program
  end

  def self.valid_season_or_episode_nr nr
    nr.to_i != 0 && nr.to_i != 99
  end

  def search_term_pattern
    "%{program_name} S%{filled_season_nr}E%{filled_episode_nr} | %{filled_season_nr}x%{filled_episode_nr}"
  end

  def interpolated_search_term
    search_term_pattern % interpolatable_attributes
  end

  def interpolatable_attributes
    {
      program_name: program.search_name,
      title: title,
      season_nr: season_nr,
      episode_nr: nr,
      filled_season_nr: "%02d" % season_nr,
      filled_episode_nr: "%02d" % nr
    }
  end

  # back and forth methods
  def self.next_episodes(episode)
    with_same_program(episode).order(:sort_nr).where('sort_nr > ?', episode.sort_nr)
  end

  def next
    self.class.next_episodes(self).first
  end

  def self.previous_episodes(episode)
    with_same_program(episode).order('sort_nr desc').where('sort_nr < ?', episode.sort_nr)
  end

  def previous
    self.class.previous_episodes(self).first
  end

  def update_sort_order
    self.sort_nr = try(:generate_sort_nr)
  end

  def generate_sort_nr
    (season_nr || 1) * 1000 + nr
  end

  def new_season?
    nr == 1
  end
end

app/controllers/admin/episodes_controller.rb
class Admin::EpisodesController < AdminAreaController
  respond_to :html, :json, :js
  before_filter :get_episode, :except => [:index, :destroy]

  def index
    if params[:program_id]
      @program = Program.friendly.find params[:program_id]
      @nav = program_nav_links

      basic_scope = @program.episodes.order('sort_nr desc').includes(:program)
    else
      basic_scope = Episode.active
        .airs_at_in_past
        .order('episodes.updated_at desc')
        .includes(:program)
    end

    @episodes = basic_scope.page params[:page]
  end

  def show
    redirect_to edit_admin_episode_path(@episode)
  end

  def update
    @episode.update_attributes params[:episode]
    redirect_to :back, :notice => 'updated!'
  end

  def destroy
    Episode.destroy params[:id]
    redirect_to :back
  end

  protected
  def get_episode
    @episode = Episode.find(params[:id])
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  layout 'fluid'
  respond_to :html, :js, :nzb

  etag { current_user.try :id }
  before_filter :authenticate_user_from_token!, only: :download
  before_filter :authenticate_user!, only: [:update, :download, :search]

  def show
    @program = program
    @episode = @program.episodes.find(params[:id])

    if stale?(etag: @episode, last_modified: @program.updated_at, public: true)
      @grouped_episodes = @program.episodes.includes(:downloads).
        order('season_nr desc, nr desc').group_by(&:season_nr)
    end
  end

  def update
    @episode  = episode
    episode.download
    respond_with episode
  end

  def download
    @episode  = episode
    @download = episode.downloads.first!
    current_user.interactions.create({
      user:             current_user,
      program:          episode.program,
      episode:          episode,
      interaction_type: 'download',
      format:           'nzb',
      end_point:        @download.download.path,
      referer:          request.referer,
      user_agent:       request.user_agent
    })

    redirect_to @download.download.expiring_url 10.seconds
  end

  def search
    @episode  = episode
    end_point = episode.search_url

    current_user.interactions.create({
      user:             current_user,
      program:          @episode.program,
      episode:          @episode,
      interaction_type: "Search",
      format:           'nzb',
      end_point:        end_point,
      referer:          request.referer,
      user_agent:       request.user_agent
    })

    redirect_to end_point
  end

  def program
    Program.friendly.find params[:program_id]
  end

  def episode
    Episode.includes(:program, :downloads).find params[:id]
  end
end

app/helpers/episode_helper.rb
module EpisodeHelper
  def current_episode_data(episode)
    return unless episode
    {
      'episode-id' => episode.id,
      'episode-nr' => episode.nr,
      'episode-season-nr' => episode.season_nr
    }
  end
end

app/views/episodes/_breadcrumb.html.haml
%ul.breadcrumb
  %li
    = link_to 'Home', root_path
    %span.divider /
  %li
    = link_to 'Programs', programs_path
    %span.divider /
  %li
    = link_to episode.program.name, program_path(episode.program)
    %span.divider /
  %li.active= truncate episode.full_episode_title

  / next+previous links
  %li.pull-right
    - if episode.next
      = link_to 'Next episode', program_episode_path(episode.program, episode.next)
    - else
      %span.muted Next episode
  %li.pull-right
    - if episode.previous
      = link_to 'Previous episode', program_episode_path(episode.program, episode.previous)
    - else
      %span.muted Previous episode
    %span.divider /

app/views/episodes/_episode.html.haml
- program ||= episode.program
%tr[episode]
  %td
    = link_to episode.full_episode_title, program_episode_path(program, episode), :class => :title
    - if episode.aired?
      .actions= render 'episodes/trusted_actions', episode: episode
  %td{:width => 220}
    - if episode.airdate
      %p= pretty_date episode.airdate, :with_year => true
      .admin-actions
        - if episode.aired?
          = link_to('Redownload', program_episode_path(episode.program, episode, :partial => :episodes), :method => :put, :remote => true, data: { :disable_with => 'loading...' }, :class => 'btn small')
    - else
      \-

app/views/episodes/_episodes.haml
- @program ||= episode.program
%tr[episode]
  %td
    = link_to episode.full_episode_title, program_episode_path(@program, episode), :class => :title
    - if current_user.try(:trusted?) && episode.airs_at.try(:past?)
      .actions= render 'episodes/trusted_actions', episode: episode
  %td{:width => 220}
    - if episode.airs_at
      %p= pretty_date episode.airs_at.to_date, :with_year => true
      - if episode.airs_at.past? && current_user.try(:admin?)
        = link_to('Redownload', admin_episode_path(episode, :partial => :episodes), :method => :put, :remote => true, :disable_with => 'loading...', :class => 'btn small')

    - else
      \-

app/views/episodes/_next_airing.html.haml
- if next_episodes.any?
  - date = nil
  %ul.nav.nav-list#next-airing
    - next_episodes.each do |episode|
      - if date != episode.airdate
        - date = episode.airdate
        %li.nav-header= pretty_date date
      %li[episode]
        = link_to episode.program do
          = episode.program_name
          - if episode.new_serie?
            %span.label.label-success New
          - elsif episode.new_season?
            %span.label.label-success New season
- else
  %p No airing episodes

app/views/episodes/_past_episode.haml
- cache [episode, episode.program] do
  %dd.panel[episode]
    %h5
      = link_to episode.program_name, episode.program
      &nbsp;-&nbsp;
      = link_to episode.full_episode_title, [episode.program, episode]
      = link_to program_episode_path(episode.program, episode), :class => 'pull-right refresh',
        :method => :put, :remote => true do
        %i.icon-repeat

    .row-fluid
      .clear= render 'episodes/trusted_actions', episode: episode
      .media
        - if episode.thumb.present?
          .pull-left= image_tag(episode.thumb.url, class: 'media-object img-polaroid', size: '300x168')
        %small= episode.description

app/views/episodes/_past_episodes.html.haml
-# A bit riskfull, need a better way
- @station ||= nil
- cache [@station, last_updated_episode, params[:page]] do
  - if past_episodes.any?
    - date = nil
    - past_episodes.each do |episode|
      - if date != episode.airdate
        - date = episode.airdate
        %dt
          %h5= pretty_date date
      = render 'episodes/past_episode', episode: episode
    .pagination
      = link_to '>', url_for(params.merge(page: (params[:page] || 1).succ)), class: 'next_page'
  - else
    %p No past episodes found

app/views/episodes/_trusted_actions.html.haml
.btn-group.trusted-actions
  = link_to search_program_episode_path(episode.program, episode), class: 'btn btn-small', rel: :nofollow do
    %i.icon-search.icon-large
    Search

  - episode.downloads.each do |download|
    = link_to download_program_episode_path(episode.program, episode, :format => :nzb),
      :title => download.origin, class: :'btn btn-small', rel: :nofollow do
      %i.icon-cloud-download.icon-large
      Download

app/views/episodes/show.html.haml
- content_for :sidebar do
  = render 'application/station_list'
- page_title "#{@episode.program.name} - #{@episode.full_episode_title}"
- meta_description @episode.description

%ul.breadcrumb
  %li
    = link_to 'Home', root_path
    %span.divider /
  %li
    = link_to 'Programs', programs_path
    %span.divider /
  %li
    = link_to @episode.program.name, program_path(@episode.program)
    %span.divider /
  %li.active= @episode.full_episode_title

  / next+previous links
  %li.pull-right
    - if @episode.next
      = link_to 'Next episode', program_episode_path(@episode.program, @episode.next)
    - else
      %span.muted Next episode
  %li.pull-right
    - if @episode.previous
      = link_to 'Previous episode', program_episode_path(@episode.program, @episode.previous)
    - else
      %span.muted Previous episode
    %span.divider /

%section
  .page-header
    %h1
      = @episode.program.name
      %small== - Season #{@episode.season_nr} - #{@episode.title}

  .media
    - if @episode.thumb.present?
      .pull-left
        %img{ src: @episode.thumb.url, class: 'media-object img-polaroid' }
    .media-body
      %dl
        %dt Description
        %dd= @episode.description
        %dt Airdate
        %dd
          - if @episode.airs_at
            = l @episode.airs_at, format: :short
          - else
            TBD
        %dt Episode info
        %dd== Season #{@episode.season_nr}, Episode #{@episode.nr}
      - if @episode.aired?
        = render 'trusted_actions', episode: @episode
%section
  %h3 Season overview
  = render 'programs/season_tabs', program: @program, grouped_episodes: @grouped_episodes, selected_episode: @episode

app/views/episodes/update.js.erb
<%- if params[:partial] == 'episodes' -%>
  $('#<%= dom_id(@episode) %>').replaceWith("<%= j render 'episode', episode: @episode %>");
  $('#<%= dom_id(@episode) %>').hide().fadeIn();
<%- else -%>
  $('#past-episodes #<%= dom_id(@episode) %>').replaceWith("<%= j render 'past_episode', episode: @episode %>");
  $('#past-episodes #<%= dom_id(@episode) %>').hide().fadeIn();
<%- end -%>